apiVersion: 1

datasources:
  - name: AMP
    type: prometheus
    access: proxy
    url: https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-622e90d2-1edc-48ed-95dd-5d4938ca6659/
    isDefault: true
    jsonData:
      httpMethod: POST
      sigV4Auth: true
      sigV4AuthType: default
      sigV4Region: us-east-1
    editable: true
